blog/urls.py
from django.urls import path
from blog.views import *

app_name = "blog"

urlpatterns = [
    path('', blog, name='index'),
    path('single', blog_single, name='single')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path('',home_page, name='index'),
    path('about/',about_page, name='about'),
    path('contact/',contact_page, name='contact'),
    path('elements/',elements_page, name='elements'),
]

blog/models.py
from django.db import models


class Post(models.Model):
    # image
    # author
    title = models.CharField(max_length=200)
    content = models.TextField()
    # tag 
    # category
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateField(null=True)
    published_time = models.TimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']
    
    def __str__(self) -> str:
        return " {} - {} ".format(self.title, self.id)

website/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    massage = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self) -> str:
        return self.name

blog/views.py
from django.shortcuts import render
from blog.models import Post
def blog(request):
    posts = Post.objects.filter(status = 1)
    context = {'posts': posts}
    return render(request, 'blog template/blog-home.html',context)

def blog_single(request):
    return render(request, 'blog template/blog-single.html')

website/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home_page(request):
    return render(request, 'website/index.html')

def about_page(request):
    return render(request, 'website/about.html')

def contact_page(request):
    return render(request, 'website/contact.html')

def elements_page(request):
    return render(request, 'website/elements.html')

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
			CSS
			============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul>
                            <li><a href="#">Visit Us</a></li>
                            <li><a href="#">Buy Tickets</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                        <div class="header-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'website:index' %}">Home</a></li>
                        <li><a href="{% url 'website:about' %}">About</a></li>
                        <li class="menu-has-children"><a href="">Blog</a>
                            <ul>
                                <li><a href="{% url 'blog:index' %}">Blog Home</a></li>
                                <li><a href="{% url 'blog:single' %}">Blog Single</a></li>
                            </ul>
                        </li>
                        <li class="menu-has-children"><a href="">Pages</a>
                            <ul>
                                <li><a href="elements.html">Elements</a></li>
                                <li class="menu-has-children"><a href="">Level 2 </a>
                                    <ul>
                                        <li><a href="#">Item One</a></li>
                                        <li><a href="#">Item Two</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="{% url 'website:contact' %}">Contact</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->
    {% block body %}

    {% endblock %}


    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">

            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message. It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div id="mc_embed_signup">
                            <form target="_blank"
                                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                method="get" class="subscription relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog template/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							<li><a href="#">Food,</a></li>
							<li><a href="#">Technology,</a></li>
							<li><a href="#">Politics,</a></li>
							<li><a href="#">Lifestyle</a></li>
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">Mark wiens</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a
									href="#">{{post.published_date}}{{post.published_time}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}}</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg' %}" alt="">
						</div>
						<a class="posts-title" href="#">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
							{{post.content}}
						</p>
						<a href="#" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">
						<li class="page-item">
							<a href="#" class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
						</li>
						<li class="page-item"><a href="#" class="page-link">01</a></li>
						<li class="page-item active"><a href="#" class="page-link">02</a></li>
						<li class="page-item"><a href="#" class="page-link">03</a></li>
						<li class="page-item"><a href="#" class="page-link">04</a></li>
						<li class="page-item"><a href="#" class="page-link">09</a></li>
						<li class="page-item">
							<a href="#" class="page-link" aria-label="Next">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-right"></span>
								</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>

			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="#">
							<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Search Posts'">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<div class="single-sidebar-widget user-info-widget">
						<img src="{% static 'img/blog/user-info.png' %}" alt="">
						<a href="#">
							<h4>Charlie Barber</h4>
						</a>
						<p>
							Senior blog writer
						</p>
						<ul class="social-links">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-github"></i></a></li>
							<li><a href="#"><i class="fa fa-behance"></i></a></li>
						</ul>
						<p>
							Boot camps have its supporters andit sdetractors. Some people do not understand why you
							should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
							andits detractors.
						</p>
					</div>
					<div class="single-sidebar-widget popular-post-widget">
						<h4 class="popular-title">Popular Posts</h4>
						<div class="popular-post-list">
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp1.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="{% url 'blog:single' %}">
										<h6>Space The Final Frontier</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp2.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="{% url 'blog:single' %}">
										<h6>The Amazing Hubble</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp3.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="{% url 'blog:single' %}">
										<h6>Astronomy Or Astrology</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp4.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="{% url 'blog:single' %}">
										<h6>Asteroids telescope</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
						</div>
					</div>
					<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
					</div>
					<div class="single-sidebar-widget post-category-widget">
						<h4 class="category-title">Post Catgories</h4>
						<ul class="cat-list">
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Technology</p>
									<p>37</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Lifestyle</p>
									<p>24</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Fashion</p>
									<p>59</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Art</p>
									<p>29</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Food</p>
									<p>15</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Architecture</p>
									<p>09</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Adventure</p>
									<p>44</p>
								</a>
							</li>
						</ul>
					</div>
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
										</div>
									</div>
									<input type="text" class="form-control" id="inlineFormInputGroup"
										placeholder="Enter email" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter email'">
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>
					</div>
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- start banner Area -->
<section class="about-banner relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					About Us
				</h1>
				<p class="text-white link-nav"><a href="index.html">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="about.html"> About Us</a>
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-6 info-left">
				<img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="">
			</div>
			<div class="col-lg-6 info-right">
				<h6>About Us</h6>
				<h1>Who We Are?</h1>
				<p>
					Here, I focus on a range of items and features that we use in life without giving them a second
					thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
					incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
					ullamco.
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Other issues we can help you with</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Rent a Car</h4>
					</a>
					<p>
						The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Cruise Booking</h4>
					</a>
					<p>
						I was always somebody who felt quite sorry for myself, what I had not got compared.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>To Do List</h4>
					</a>
					<p>
						The following article covers a topic that has recently moved to center stage–at least it seems.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Food Features</h4>
					</a>
					<p>
						There are many kinds of narratives and organizing principles. Science is driven by evidence.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End other-issue Area -->
{% endblock %}

templates/website/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>this is a Home page<h1></h1>
    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
    </p>
</body>
</html>